/* Do not edit this file. */
/* Any state information should be in /store/app.js */

import { createStore } from "vuex";

import app from "@/store/app";

const store = createStore({
  state: {},
  mutations: {},
  actions: {},
  modules: {
    app,
  }
});

export default store;
